### ISSUE TITLE
Automated method of setting default Start and taskbar layout for images?

### ISSUE THREAD

**Issue by loosus456** [Microsoft/windows-itpro-docs#109]
I don't see a completely automated method in the documentation for setting the default Start layout and default taskbar layout for new users in an automated fashion.

**Group Policy**: does not set a simple default layout; instead, it locks the layout so that the user cannot make persistent changes.

**ICD**: sets a default layout but requires manual intervention from the IT professional.  The last step in the documentation directs the IT professional to "double-click the ppkg file and allow it to install."

Most IT professionals would want this to be automated as part of the imaging process so that no manual intervention is required at all.

Would a solution be setting the default Start layout and taskbar layout via the **Import-StartLayout** PowerShell cmdlet?  Would that import both the Start layout and taskbar layout for new users without locking either one from the user?  (As far as I am aware, this cmdlet uses the same XML file referenced in the documentation.)  If so, this would also allow IT professionals to make it part of the imaging deployment process as an automated script, requiring no intervention from the IT professional.

In addition, regardless of whether this works or not, is it a supported method?

**Comment by jdeckerMS** [comment]
Admins can use either Group Policy or MDM to deploy a partial Start layout which permits users to add their own tile groups. 

Import-StartLayout applies the XML to a mounted image, and is referenced in this topic: https://technet.microsoft.com/en-us/itpro/windows/manage/customize-windows-10-start-screens-by-using-group-policy#bkmk-howstartscreencontrolworks 

I will open a request for adding instructions for default Start layout to the documentation on imaging Windows 10. I can't give you an estimate of when that might be added, since it will need to be prioritized with other work requests. Thanks for the suggestion!

**Comment by loosus456** [comment]
That cmdlet can be used with both mounted images and the online image (i.e., the image you're currently using). That's why I felt that it belongs in the existing documentation because it accomplishes a default layout just like ICD does, just without manual intervention from the IT professional.

In any case, thanks for looking.
