### ISSUE TITLE
Windows Event Forwarding / Missing information

### ISSUE THREAD

**Issue by mschilt** [Microsoft/windows-itpro-docs#86]
windows-itpro-docs/windows/keep-secure/use-windows-event-forwarding-to-assist-in-instrusion-detection.md

I really like the content and structure of that article. Its the best source for Windows Event Forwarding I could find. I would like to share what I found when tuning a Server to receive events from around 50k Clients. 
* all transactions (wsman and receiving logs) are based on the http.sys webserver. This webserver fills the disk with logs when clients send log. Disabling this logging is important for scalability. Change parameter EnableErrorLogging see KB820729.
* Session timeout of http is also set to 30 seconds. Most sessions have a duration of not longer than 2-3 seconds. Reducing the session timeout can be beneficial (see https://msdn.microsoft.com/en-us/library/windows/desktop/cc307237(v=vs.85).aspx) .
* by default Windows has a timeout of closed TCP connections of 30 seconds. This leads to consumed resources if this parameters is not being tuned. reducing this timeout could be beneficial (see https://technet.microsoft.com/en-us/library/cc938217.aspx)
* Putting wsman/WinRM and Wecsvc in its own svchost processes can help should the hosting svchost consume too much resources (CPU/Memory)
** sc config WinRM type= own
** sc config Wecsvc type= own
* According to the article some registry keys are being created when clients subscribe. Unfortunately the location of that registry keys are not written. Could you please add this?
* I also saw that the security log if flooded with 4624 and 4634 Events. Does this also need some tuning? Do you recommend to turn it off?

**Comment by tedhardyMSFT** [comment]
Hi! Those are some good additions. I'll make some changes using them.

Some In my experience having a WEC server with over 10k leads to a potentially unstable system, event with tuning leads to network exhaustion or registry contention for updating all of the client bookmarks. The 10k by 10k box is for a maximally stable system that can be set up and leave headroom for surges but also not require special maintenance and techniques for using (many customers still use Event Viewer for modifying the Subscription parameters and at that client load the UI becomes unusable due to enumerating all of the subscription clients.)

also the Security/4624 and Security/4634 are normal (just logon/logoff) and depending on your security posture and maturity can be useful or noise. Initially I recommend heavily filtering on those (specifically filter out LogonType=3 (network) to focus on user, batch, and service activity; later once those are set then add in logonType=3 for mesh analysis. Alternatively including LogonType=3 and just logging them (no analysis) can be useful in an incident response to answer questions such as "what other machines did this compromised account access over the network?"
